category/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "category"
urlpatterns = [
    path("categoryadd/", views.CategoryAdd, name="categoryadd"),
    path("categoryread/", views.CategoryView.as_view(), name="categoryread"),
    path("deletecategory/<int:id>", views.delete_category, name="deletecategory"),
    path("<int:id>", views.update_category, name="updatecategory"),
]

login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path("", views.loginUser, name="login"),
    path("fortgotpass/", views.ForgotPass, name="fortgotpass"),
    path("logout/", views.user_logout, name="logout"),
]

product/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "product"
urlpatterns = [
    path("productadd/", views.ProductAdd, name="productadd"),
    path("productread/", views.ProductView.as_view(), name="productread"),
    path("deleteuser/<int:id>/", views.delete_product, name="deleteproduct"),
    path("<int:id>/", views.update_product, name="updateproduct"),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url

# url name for users url, this will help us to easily find url
app_name = "user"

# path for user related work, when we access 'url:useradd' than the control of
# website will enter UserAdd view similarly with other urls
urlpatterns = [
    path("", views.UserAdd, name="useradd"),
    path("userread/", views.UserView.as_view(), name="userread"),
    path("changePass/", views.ChangePass, name="changepass"),
    path("<int:id>/", views.UpdateUser, name="updateuser"),
    path("deleteuser/<int:id>/", views.DeleteUser, name="deleteuser"),
    path("register/", views.UserRegister, name="register"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("profile/<int:id>/", views.Profile, name="profile"),
]

userCRUD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views  # import this

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("user/", include("user.urls")),
    path("product/", include("product.urls")),
    path("category/", include("category.urls")),
    path("login/", include("login.urls")),
    # ---------------------- for reset email configuration ----------------------
    # when this url is hit
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="resetPass/mailSent.html"
        ),
        name="mailSent",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="resetPass/mailConfirm.html"
        ),
        name="mailConfirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="resetPass/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    # ----------------------------------------------------------------------------
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/models.py
from django.db import models

# Create your models here.

login/forms.py
from django import forms
from django.core.exceptions import ValidationError
from user.models import User
from django.contrib.auth.hashers import (
    check_password,
)

# class for login form
class LoginForm(forms.Form):

    email = forms.EmailField(
        error_messages={"required": ""},
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter Email",
            }
        ),
    )

    password = forms.CharField(
        error_messages={"required": ""},
        widget=forms.PasswordInput(
            attrs={"placeholder": "Enter password", "class": "password"}
        ),
    )
    rememberMe = forms.CharField(
        widget=forms.CheckboxInput(
            attrs={
                "id": "rememberMe",
            }
        ),
    )

    def clean(self):
        cleaned_data = super().clean()

        valEmail = self.cleaned_data.get("email")

        if not valEmail:
            raise ValidationError("please enter Email")

        valpassword = self.cleaned_data.get("password")

        if not valpassword:
            raise ValidationError("please enter password")

        verifyUser = User.objects.filter(email=valEmail).first()

        if not verifyUser:
            raise ValidationError("user doesn't exists")

        if not verifyUser.is_active:
            raise ValidationError("user is not active, check your mail")

        if not check_password(valpassword, verifyUser.password):
            raise ValidationError("username and  password didnt matched")


# different class for password change
class ChangePassForm(forms.Form):

    email = forms.EmailField(
        error_messages={"required": "please enter Email"},
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter Email",
            }
        ),
    )

login/views.py
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render
from .forms import LoginForm
from django.contrib.auth import logout
from .forms import ChangePassForm
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from user.models import User as users
from django.contrib.auth import (
    authenticate,
    login,
)

# Create your views here
# ------------------ Views for logging in --------------------------
def loginUser(request):

    if request.method == "POST":
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():

            fname = loginForm.cleaned_data["email"]
            pw = loginForm.cleaned_data["password"]
            fremember = loginForm.cleaned_data["rememberMe"]

            userss = users.objects.get(email=fname)

            user = authenticate(username=fname, password=pw)
            login(request, user)

            # session created
            request.session["user"] = userss.email

            # return response
            messages.success(request, "User Logged in successfully")
            response = HttpResponseRedirect("../user/")

            if fremember == "True":
                print("entered cookie")
                response.set_cookie("cookieusername", fname)
            else:
                print("cookie not set")

            return response

        else:
            print("invalid form")
    else:
        if request.COOKIES.get("cookieusername"):
            return HttpResponseRedirect("../user/")
        else:
            print("username cookie not set")

        loginForm = LoginForm()

    return render(request, "login.html", {"form": loginForm})


# ------------------ function for changing password --------------------------
def ForgotPass(request):

    if request.method == "POST":

        loginForm = ChangePassForm(request.POST)
        if loginForm.is_valid():

            fname = loginForm.cleaned_data["email"]
            associated_users = users.objects.filter(email=fname)

            print("hiii i am associated_users", associated_users, fname)

            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "resetPass/password_reset_email.txt"
                    print(email_template_name)
                    c = {
                        "email": user.email,
                        "domain": "127.0.0.1:8000",
                        "site_name": "anupam.siwakoti@gmail.com",
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        "token": default_token_generator.make_token(user),
                        "protocol": "http",
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(
                            subject,
                            email,
                            "admin@example.com",
                            [user.email],
                            fail_silently=False,
                        )
                    except BadHeaderError:
                        return HttpResponse("Invalid header found.")
                    return redirect("../../password_reset/done/")
        else:
            print("invalid form")
    else:
        loginForm = ChangePassForm()
    return render(request, "resetPass/forgotPass.html", {"form": loginForm})


# ------------------ function for logout --------------------------
def user_logout(request):
    response = HttpResponseRedirect("../")
    response.delete_cookie("cookieusername")
    logout(request)
    return response

templates/acc_active_email.html
{% load static %} {% autoescape off %} Hi {{ user.first_name }}, Please click on
the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %} {% endautoescape %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>User Add/Read</title>
    <!-- Google Font: Source Sans Pro -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback"
    />
    <!-- Font Awesome -->
    {% block csspart %}
    <link
      rel="stylesheet"
      href="{%static 'plugins/fontawesome-free/css/all.min.css' %}"
    />
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static 'dist/css/adminlte.min.css' %}" />
    <!-- overlayScrollbars -->
    <link
      rel="stylesheet"
      href="{%static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}"
    />
    {% endblock csspart %}
  </head>

  {% block bodytag %}
  {% endblock bodytag%} 

  {% block nav%}
    <div class="wrapper">
      <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"
              ><i class="fas fa-bars"></i
            ></a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Home</a>
          </li>
          <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
          </li>

          <li class="nav-item d-none d-sm-inline-block"><a href="{% url 'user:profile' user.id %}" class="nav-link">Profile</a></li>
          <li class="nav-item d-none d-sm-inline-block"><a href="{% url 'login:logout' %}" class="nav-link">Logout</a></li>
          <li class="nav-item d-none d-sm-inline-block" data-toggle="modal" data-target="#myModal"  ><a href="#" class="nav-link">Change Password</a></li>

        </ul>
      </nav>
                    <div id="myModal" class="modal fade" role="dialog">
                      <div class="modal-dialog">
                        <!-- Modal content-->
                        <div class="modal-content">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                          </div>
                          <div class="modal-body">
                                  <div class="tab-pane changePasswordForm" id="">
                                    <h6>Change Password</h6>
                                    <form action="{% url 'user:changepass' %}" method="POST">
                                        {% csrf_token %}
                                        <input class="form-control form-control-sm mb-2 oldpass" name="oldPass" type="password"
                                            placeholder="Old Password" reqiured>
                                        <input class="form-control form-control-sm mb-2 newPass1" name="newPass1" type="password"
                                            placeholder="New Password" reqiured>
                                        <input class="form-control form-control-sm mb-2 newPass2" name="newPass2" type="password"
                                            placeholder="Re-enter New Password" reqiured>
                                        <input type="submit" name ="changePassword" class="btn btn-primary btn-sm" value="Change Password">

                                    </form>
                                </div>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </div>

                      </div>
                  </div>
      <!-- Main Sidebar Container -->
      <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="index3.html" class="brand-link">
          <img
            src="{%static 'dist/img/AdminLTELogo.png' %}"
            alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3"
            style="opacity: 0.8"
          />
          <span class="brand-text font-weight-light">AdminLTE 3</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
          <!-- Sidebar user panel (optional)  {%static 'dist/img/traveler1.jpg' %} -->
          <div class="user-panel mt-3 pb-3 mb-3 d-flex">

          
            <div class="image">

    {%if user.profile_pic %}
              <img
                src="{{ user.profile_pic.url }}"
                class="img-circle elevation-2"
                alt="User Image"
              />
    {% else %}
              <img
                src="{% static 'dist/img/user.png' %}"
                class="img-circle elevation-2"
                alt="User Image"
              />
      {% endif %}
            </div>
            <div class="info">
              <a href="#" class="d-block">{{ user.first_name }}</a>
            </div>
          </div>

          <!-- SidebarSearch Form -->
          <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
              <input
                class="form-control form-control-sidebar"
                type="search"
                placeholder="Search"
                aria-label="Search"
              />
              <div class="input-group-append">
                <button class="btn btn-sidebar">
                  <i class="fas fa-search fa-fw"></i>
                </button>
              </div>
            </div>
          </div>

          <!-- Sidebar Menu -->
          <nav class="mt-2">
            <ul
              class="nav nav-pills nav-sidebar flex-column"
              data-widget="treeview"
              role="menu"
              data-accordion="false"
            >
            {% if user.admin %}
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-users"></i>
                  <p>
                    USER
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'user:useradd' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Add User</p>
                    </a>
                  </li>
                </ul>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'user:userread' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>View User</p>
                    </a>
                  </li>
                </ul>
              </li>
            {% endif %}
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon far fa-arrow-alt-circle-right"></i>
                  <p>
                    Product
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'product:productadd' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Add Product</p>
                    </a>
                  </li>
                </ul>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'product:productread' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>View Product</p>
                    </a>
                  </li>
                </ul>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="nav-icon fas fa-edit"></i>
                  <p>
                    Category
                    <i class="fas fa-angle-left right"></i>
                  </p>
                </a>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'category:categoryadd' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Add Category</p>
                    </a>
                  </li>
                </ul>
                <ul class="nav nav-treeview">
                  <li class="nav-item">
                    <a href="{% url 'category:categoryread' %}" class="nav-link">
                      <i class="far fa-circle nav-icon"></i>
                      <p>View Category</p>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </nav>
          <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
      </aside>
      {% endblock nav%}
      
      {% block bodycontent%} 
      {% endblock bodycontent%}

      {% block redirect%}
      {% endblock redirect%}
      <!-- /.content-wrapper -->
      <footer class="main-footer">
        <strong
          >Copyright &copy; 2014-2021
          <a href="https://adminlte.io">@anupam</a>.</strong
        >
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
          <b>Version</b> 3.1.0
        </div>
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
      </aside>
      <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->

    {% block addjquery %}
    <!-- jQuery -->
    <script src="{%static 'plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{%static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge("uibutton", $.ui.button);
    </script>
    <!-- Bootstrap 4 -->
    <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- overlayScrollbars -->
    <script src="{%static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{%static 'dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{%static 'dist/js/demo.js' %}"></script>
    <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
    {% endblock addjquery %}
  </body>
</html>

templates/categoryread.html
{%extends "base.html" %} {% load static %} 
    <!-- Font Awesome -->

    {% block csspart %}
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- DataTables -->
  <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">

  </head>
  {% endblock csspart %}

  {%block bodycontent%}
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">
                <h1>General Form</h1>
              </div>
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item active">General Form</li>
                </ol>
              </div>
            </div>
          </div>
          <!-- /.container-fluid -->
          
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Category</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                  {% for message in messages %}
                  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    {{ message }}
                  </div>
                  {% endfor %}
                <table id="example2" class="table table-bordered table-hover">
                  <thead>
                  <tr>
                    <th>Category name</th>
                    <th>vendor</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>
                  {% for categories in category %}
                    <tr>
                      <td>{{categories.name}}</td>
                      <td>{{categories.vendor}}</td>
                      <td>
                      <a class="btn btn-success" href="{% url 'category:updatecategory' categories.id %}"
                        role="button">Edit</a>
                      <form action="{% url 'category:deletecategory' categories.id %}" method="POST" class=d-inline>
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Delete">
                      </form>
                    </td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
        <!-- /.content -->
    </div>
      <!-- /.content-wrapper -->
    {%endblock bodycontent%}

    {%block addjquery%}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Page specific script -->
            <script
      src="https://kit.fontawesome.com/b45233a9f7.js"
      crossorigin="anonymous"
    ></script>
<script>
  $(function () {
    $("#example1").DataTable({
      "responsive": true, "lengthChange": false, "autoWidth": false,
      "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
    {% endblock addjquery %}
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
  {% load static%}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    />
    <link rel="stylesheet" href="{% static 'dist/css/form.css' %}" />

    <title>User Login</title>
  </head>

  <body>
    <form action="{% url 'login:login' %}" method="POST" novalidate>
      {% csrf_token %}
      <div class="form-control">
        {% for message in messages %}
        <div
          class="alert alert-{{message.tags}} alert-dismissible fade show"
          role="alert"
        >
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message }}
        </div>
        {% endfor %}
        <h2 class="border-bottom text-center">Sign-In</h2>
        <br />

        <div class="list">
          {% if form.errors %}
          <ul>
            {% for key,value in form.errors.items %}
            <li class="list-errors">{{ value|escape }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>

        <div class="pt-2">
          <div class="inputWithIcon inputIconBg">
            {{form.email}}
            <i class="fa fa-envelope fa-lg fa-fw bg"></i>
          </div>
          <div class="inputWithIcon inputIconBg">
            {{form.password}}
            <i class="fas fa-key fa-lg fa-fw bg"></i>
            <span class="eye">
              <i class="fas fa-eye togglePassword"></i>
            </span>
          </div>
          {{form.rememberMe}}
          <label for="rememberMe"> Remember Me</label>
          <input class="btn" name="submit" type="submit" value="Continue" />

          <div class="text-center">
            <p>
              <small
                ><a href="{% url 'login:fortgotpass' %}"
                  >Forgot your password?</a
                ></small
              >
              <small><a href="{% url 'user:register' %}">register</a></small>
            </p>
          </div>
        </div>
      </div>
    </form>

    <script src="{% static 'dist/js/script.js' %}"></script>
    <script src="{%static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
  {% load static%}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Register</title>

    <link
      href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
      rel="stylesheet"
      id="bootstrap-css"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
    />
    <link rel="stylesheet" href="{% static 'dist/css/register-form.css' %}" />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>
  <body>
    <form method="POST" action="{% url 'user:register' %}" novalidate>
      {% csrf_token %}
        <div class="list">
          {% if form.errors %}
          <ul class="errorlist">
            {% for key,value in form.errors.items %}
            <li class="list-errors">{{ value|escape }}</li>
            {% endfor %}
          </ul>
          {% endif %}
        </div>
        <img
          src="{%static 'dist/img/AdminLTELogo.png' %}"
          alt="AdminLTE Logo"
          class="brand-image img-circle elevation-3"
          style="opacity: 0.8"
        />
      </a>
      <label>
        <div class="inputWithIcon inputIconBg">
          {{form.address}}
          <i class="fas fa-map-marker-alt fa-lg fa-fw bg"></i>
        </div>
      </label>
      <label>
        <div class="inputWithIcon inputIconBg">
          {{form.email}}
          <i class="fa fa-envelope fa-lg fa-fw bg"></i>
        </div>
      </label>
      <label>
        <div class="inputWithIcon inputIconBg">
          {{form.first_name}}
          <i class="fa fa-user fa-lg fa-fw bg"></i>
        </div>
      </label>
      <label>
        <div class="inputWithIcon inputIconBg">
          {{form.last_name}}
          <i class="fa fa-user fa-lg fa-fw bg"></i>
        </div>
      </label>
      <label>
        <div class="inputWithIcon inputIconBg">
          {{form.password}}
          <i class="fas fa-lock fa-lg fa-fw bg"></i>
          <span class="eye">
            <i class="fas fa-eye togglePassword"></i>
          </span>
        </div>
      </label>
      <button type="submit">submit</button>
      <small><a href="{% url 'login:login' %}">login</a></small>
    </form>

    <script src="{% static 'dist/js/register-form.js' %}"></script>
  </body>
</html>